- hosts: nagios
  become: true
  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Nagios Core + Apache
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - nagios3
        - nagios-plugins-basic
        - nagios-nrpe-plugin

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create directory for Nagios configs
      file:
        path: /etc/nagios3/conf.d
        state: directory

    - name: Copy Skillswap monitoring config
      copy:
        src: ../../../nagios/conf.d/skillswap.cfg
        dest: /etc/nagios3/conf.d/skillswap.cfg
        mode: '0644'

    - name: Restart Nagios
      service:
        name: nagios3
        state: restarted
