- hosts: nagios
  become: true
  tasks:

    - name: apt update
      apt:
        update_cache: yes

    - name: Install Nagios + Apache
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - nagios3
        - nagios-plugins-basic
        - nagios-nrpe-plugin

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy Nagios check config
      copy:
        src: ../../../nagios/conf.d/skillswap.cfg
        dest: /etc/nagios3/conf.d/skillswap.cfg
        mode: '0644'

    - name: Restart Nagios
      service:
        name: nagios3
        state: restarted
