; [minikube]
; minikube-host ansible_host=100.26.180.139 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/skillswap.pem

; [nagios]
; nagios-host ansible_host=18.232.35.216 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/skillswap.pem


[minikube]
minikube-host ansible_connection=local

[nagios]
nagios-host ansible_host=18.232.35.216 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/skillswap.pem
