name: CI/CD Pipeline - Build, Push and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build_and_push:
    name: Build React → Docker → Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies & Build
        run: |
          npm install
          chmod +x node_modules/.bin/react-scripts
          npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.IMAGE_NAME }}:latest
          platforms: linux/amd64

  